Added dowloader support for tokenizer file
freshlybuiltongithub/freshylbuiltimagejaano pull request #9
Opened 2020-08-02 17:34 UTC by ravi5175

What's New
- Added get_token.py script to add download support to the tokenizer

2020-08-02 18:02 UTC, devkapilbansal requested changes
Also we don't need tqdm in get_token

2020-08-02 18:02 UTC, KapilBansal320 commented on freshlybuiltimagejaano/test_generator.py
> +            print("tokenizer load successful")
Maybe dir path is also needed here

2020-08-03 06:26 UTC, devkapilbansal approved these changes

2020-08-03 06:42 UTC, vishal2612200 approved these changes

2020-08-03 06:42 UTC, vishal2612200 commented on freshlybuiltimagejaano/test_generator.py
> +            print("tokenizer load successful")
Looks better.

2020-08-03 06:43 UTC, merged